#  Numpy Exercise

In [1]:
import numpy as np

In [2]:
arr=np.array([45,12,69,10])
arr

array([45, 12, 69, 10])

In [3]:
arr.ndim                                            # For check dimensional of array

1

In [4]:
arr.size                                             # For check size of array i.e. howmany values in the array

4

In [5]:
arr.dtype                                             # check data type of array

dtype('int32')

In [6]:
arr

array([45, 12, 69, 10])

In [7]:
arr.shape

(4,)

In [8]:
ones_matrix=np.ones((3,4))                              # Ones Matrix
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
ones_matrix.dtype

dtype('float64')

In [10]:
one=np.ones((4,4),dtype=int)                      # Ones Matrix data type is integer
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
one=np.ones((4,4),dtype=bool) 
print(one)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
em=np.empty((2,3))
print(em)

[[7.56602523e-307 1.29060531e-306 2.04720783e-306]
 [1.11258277e-307 1.33511562e-306 6.23040373e-307]]
