#  Random Sampling

In [1]:
import numpy as np
import random

In [2]:
np.random.random(2)                                                       # Create 2 random values

array([0.44072607, 0.22803884])

In [5]:
np.random.random((4,4))

array([[0.32991295, 0.60884173, 0.84694221, 0.21137622],
       [0.48159941, 0.20165973, 0.49734273, 0.07260251],
       [0.08669873, 0.76304008, 0.45307693, 0.07888409],
       [0.46795904, 0.31926632, 0.51473146, 0.83537231]])

In [6]:
np.random.randint(4,7)

5

In [9]:
np.random.randint(4,40,(10,10))                                          # Random array in integer format

array([[23, 19, 21, 12, 23, 32, 28,  6,  6, 35],
       [31, 38,  7, 10, 20, 11, 34, 27, 27, 24],
       [21, 39, 18, 22, 11, 34, 35, 31,  9, 37],
       [20, 20, 23, 31, 10, 27, 16, 37, 15, 35],
       [27, 33, 31, 14, 15, 36, 11,  6, 35,  7],
       [ 4, 22, 19, 35, 34,  8, 14, 10, 38, 15],
       [18, 22, 18, 18, 20, 15,  9,  8, 34, 20],
       [38, 36,  8, 18, 31, 34, 30, 21, 32, 13],
       [19, 29, 28, 27, 32, 15, 16, 31, 34, 14],
       [39, 25, 38, 23, 29, 29, 11, 25, 38, 21]])

In [12]:
np.random.randint(4,40,(3,5,6))                                  # 3 Random array of 5 row and 6 column,

array([[[26, 32, 29, 30, 33, 15],
        [11, 24, 21, 22, 13,  6],
        [37,  6, 17, 37, 15, 39],
        [35, 14, 38, 31, 15, 25],
        [19, 26,  4, 22,  5, 30]],

       [[ 9, 27, 15, 20, 27, 21],
        [18, 36, 25, 20, 26, 34],
        [34, 23, 33, 25, 18, 11],
        [34, 16,  7, 35, 25, 23],
        [ 9, 15, 31, 36, 34, 26]],

       [[13, 12, 11, 19,  7, 28],
        [ 8,  8, 38, 35, 14, 33],
        [ 5,  8, 16, 22, 25, 27],
        [24, 16, 16,  4, 23, 10],
        [19, 14,  6, 15, 24, 11]]])

In [14]:
np.random.seed(9)
np.random.randint(4,40,(3,5,6))

array([[[32, 26,  5, 26, 31, 37],
        [33, 32,  4, 28, 14, 33],
        [16, 22, 26,  5, 39, 15],
        [23, 13, 20, 17, 37, 17],
        [33, 26,  8, 39,  4, 14]],

       [[20,  8,  9, 28, 23, 34],
        [ 8, 12,  4,  5, 38, 31],
        [17, 11, 19,  6, 33, 38],
        [23, 23, 21, 36, 38, 20],
        [18, 15, 33, 11, 31, 36]],

       [[22, 31,  4,  5, 27, 37],
        [26, 22, 25, 36, 20, 25],
        [23, 27, 34, 16, 19, 15],
        [26,  6, 16, 25, 25, 22],
        [14, 26, 33, 39,  5, 10]]])

In [15]:
np.random.seed(9)                   # Seed() if we call this process seed() function always return the same values
np.random.randint(4,40,(3,5,6))

array([[[32, 26,  5, 26, 31, 37],
        [33, 32,  4, 28, 14, 33],
        [16, 22, 26,  5, 39, 15],
        [23, 13, 20, 17, 37, 17],
        [33, 26,  8, 39,  4, 14]],

       [[20,  8,  9, 28, 23, 34],
        [ 8, 12,  4,  5, 38, 31],
        [17, 11, 19,  6, 33, 38],
        [23, 23, 21, 36, 38, 20],
        [18, 15, 33, 11, 31, 36]],

       [[22, 31,  4,  5, 27, 37],
        [26, 22, 25, 36, 20, 25],
        [23, 27, 34, 16, 19, 15],
        [26,  6, 16, 25, 25, 22],
        [14, 26, 33, 39,  5, 10]]])

In [16]:
np.random.rand(5)                                       # rand() for random values but always return values less than 1

array([0.18315273, 0.10931052, 0.53957552, 0.28929928, 0.10305405])

In [17]:
np.random.rand(5,5)

array([[0.49060155, 0.63209168, 0.03796922, 0.50010792, 0.08354343],
       [0.79131823, 0.75803602, 0.26227322, 0.10085859, 0.91719271],
       [0.51746024, 0.13353968, 0.11254311, 0.84164115, 0.54607474],
       [0.26101658, 0.57582552, 0.31385261, 0.79162319, 0.49309072],
       [0.96515818, 0.52031194, 0.9030216 , 0.24980456, 0.5214873 ]])

In [20]:
np.random.randn(4,5)                                           # randn() return values in -ve/+ve format.

array([[-0.24080791,  0.27080725, -1.09553963,  2.40134297, -0.27990974],
       [ 2.0308008 , -0.08193947, -1.21862641, -0.8068705 ,  1.31804189],
       [-0.57863866,  0.0820525 ,  1.39591049,  1.08187963, -1.01656093],
       [-0.2919983 ,  1.55935821, -0.54630018,  0.96059071,  0.21121052]])

In [22]:
np.random.randn(4,4)

array([[-0.77605336, -0.64759606, -0.48733461,  0.37526388],
       [-1.03600638, -0.13392398,  0.3848789 ,  0.35439691],
       [ 0.34263762, -0.59730083, -0.18854823,  0.70032497],
       [-1.32562343,  0.93702845, -0.45068969,  0.93112913]])

In [23]:
x=[41,15,20,1,78]
np.random.permutation(x)

array([78, 15,  1, 20, 41])

In [24]:
np.random.permutation(x)

array([ 1, 20, 41, 15, 78])