# Numpy Array Slicing

In [1]:
import numpy as np

In [2]:
ar=np.arange(0,100).reshape(10,10)
print(ar)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [3]:
ar[2,6]                                                  # Access 26 

26

In [4]:
ar[0]                                                      # first row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ar[:,4]                                                   # Fourth column

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [6]:
ar.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
ar[1:5,2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

In [8]:
ar[:, 0:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [9]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
ar[1:6,2:6]                   # 1st row to 5th row and 2nd culumn to 5th column

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55]])

In [11]:
ar[4:6,3:5]

array([[43, 44],
       [53, 54]])

In [12]:
ar[3:9]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [13]:
ar[:,4:7]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26],
       [34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66],
       [74, 75, 76],
       [84, 85, 86],
       [94, 95, 96]])

In [14]:
ar[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
ar[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
ar[:,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
ar.itemsize                                         # Item size of every element

4

In [18]:
ar.dtype

dtype('int32')

# Numpy Array Concatination and Split

In [19]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
a1=np.arange(17,33).reshape(4,4)
a1

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [21]:
list1=[45,52,15,12]
list2=[98,36,55,74,10]

In [22]:
list1+list2                                                  # Concatenate two list

[45, 52, 15, 12, 98, 36, 55, 74, 10]

In [23]:
np.concatenate((a,a1))                                       # Concatenate two matrix 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [24]:
np.concatenate((a,a1),axis=1)                               # Concatenate matrix row wise

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [25]:
np.vstack((a,a1))                                          

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [26]:
np.hstack((a,a1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [27]:
np.split(a,2)                                      # Split matrix in 2 part, but matrix split in list format

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [28]:
l=np.split(a,2)
l

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [29]:
type(l)

list

In [30]:
l[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
l[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
a
a1

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [34]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
a1

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [36]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [37]:
list=np.split(a,2)

In [38]:
type(list)

list

In [39]:
list[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
list[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
type(list[0])

numpy.ndarray

In [42]:
a1

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [43]:
np.split(a1,2,axis=1)                        

[array([[17, 18],
        [21, 22],
        [25, 26],
        [29, 30]]), array([[19, 20],
        [23, 24],
        [27, 28],
        [31, 32]])]

In [44]:
d1=np.array([45,12,41,15,96,20])        # Split 1d array 

In [45]:
d1

array([45, 12, 41, 15, 96, 20])

In [46]:
np.split(d1,[1,4])

[array([45]), array([12, 41, 15]), array([96, 20])]

In [47]:
aw=np.arange(100,200).reshape(10,10)

In [48]:
aw

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [49]:
aw[0]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [50]:
aw[1]

array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [52]:
aw[0:1]

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [53]:
aw[:,0]

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [54]:
aw

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [55]:
aw[:,8]

array([108, 118, 128, 138, 148, 158, 168, 178, 188, 198])

In [57]:
aw[:, 0:5]

array([[100, 101, 102, 103, 104],
       [110, 111, 112, 113, 114],
       [120, 121, 122, 123, 124],
       [130, 131, 132, 133, 134],
       [140, 141, 142, 143, 144],
       [150, 151, 152, 153, 154],
       [160, 161, 162, 163, 164],
       [170, 171, 172, 173, 174],
       [180, 181, 182, 183, 184],
       [190, 191, 192, 193, 194]])

In [58]:
aw[:, 4:5]

array([[104],
       [114],
       [124],
       [134],
       [144],
       [154],
       [164],
       [174],
       [184],
       [194]])

In [59]:
aw

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [61]:
aw[0:,4:6]

array([[104, 105],
       [114, 115],
       [124, 125],
       [134, 135],
       [144, 145],
       [154, 155],
       [164, 165],
       [174, 175],
       [184, 185],
       [194, 195]])

In [62]:
aw

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [64]:
aw[:,2:5]

array([[102, 103, 104],
       [112, 113, 114],
       [122, 123, 124],
       [132, 133, 134],
       [142, 143, 144],
       [152, 153, 154],
       [162, 163, 164],
       [172, 173, 174],
       [182, 183, 184],
       [192, 193, 194]])

In [66]:
aw[4:0,]

array([], shape=(0, 10), dtype=int32)

In [67]:
a=np.array([[45,45,41,78],[10,20,30,40],[100,200,300,400]])
a

array([[ 45,  45,  41,  78],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [69]:
a[0:0,1:2]

array([], shape=(0, 1), dtype=int32)

In [70]:
aw

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [71]:
aw[3:9,3:9]

array([[133, 134, 135, 136, 137, 138],
       [143, 144, 145, 146, 147, 148],
       [153, 154, 155, 156, 157, 158],
       [163, 164, 165, 166, 167, 168],
       [173, 174, 175, 176, 177, 178],
       [183, 184, 185, 186, 187, 188]])