# Numpy Functions

In [1]:
import numpy as np

In [2]:
np.linspace(4,10,5)                                                    # linspace()

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

In [3]:
ar=np.arange(1,10).reshape(3,3)                                          # reshape()
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ar.transpose()                                                          # transpose() the matrix
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Mathematics Operation 

In [6]:
ar1=np.array([[10,20,30],[40,50,60],[70,80,90]])
ar1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
ar+ar1                                                              # Add two matrix by element wise

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [8]:
np.add(ar,ar1)                                                        # add()

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [9]:
ar1-ar                                                                   # subtract() matrix   

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [10]:
np.subtract(ar1,ar)

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [11]:
ar1/ar                                                                      # Divide the matrix

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [12]:
np.divide(ar1,ar)                                                            # divide()

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [13]:
ar*ar1                                                                      # Multiply matrix

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [14]:
np.multiply(ar,ar1)                                                        # multiply()

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [15]:
ar@ar1                                             # " @ " Function for multiply using matrix first row first column

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [16]:
ar.dot(ar1)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [17]:
ar1.max()                                               # max() find maximum value from matrix

90

In [18]:
ar.max()

9

In [19]:
ar1.argmax()                                 

8

In [20]:
ar1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
ar1.max(axis=0)

array([70, 80, 90])

In [22]:
ar.max(axis=1)

array([3, 6, 9])

In [23]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
ar1.min()                                                     # Minimum value  min()

10

In [25]:
ar.min(axis=0)

array([1, 2, 3])

In [26]:
ar1.min(axis=1)

array([10, 40, 70])

In [27]:
np.mean(ar1)                                                 # Find mean()

50.0

In [28]:
np.mean(ar)

5.0

In [29]:
np.sqrt(ar1)                                                  # Find sqrt() of every element

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [30]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [31]:
np.std(ar1)                                                  # Find standard division

25.81988897471611

In [32]:
np.std(ar)

2.581988897471611

In [33]:
np.exp(ar1)                                                  # Find exponent of every element

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

In [34]:
np.exp(ar)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [35]:
np.log(ar1)                                                 # Find log of every element of matrix

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

In [36]:
np.log(ar)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [37]:
np.log10(ar1)                                           # Log base 10      

array([[1.        , 1.30103   , 1.47712125],
       [1.60205999, 1.69897   , 1.77815125],
       [1.84509804, 1.90308999, 1.95424251]])

In [38]:
np.log10(ar)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [41]:
n=np.linspace(1,5,5)
n

array([1., 2., 3., 4., 5.])

In [42]:
at=np.arange(1,10).reshape(3,3)
at

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a=at.transpose()
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
a.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
at

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.add(a,at)

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [51]:
a+at

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [53]:
np.subtract(a,at)

array([[ 0,  2,  4],
       [-2,  0,  2],
       [-4, -2,  0]])

In [54]:
np.multiply(a,at)

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [55]:
np.divide(a,at)

array([[1.        , 2.        , 2.33333333],
       [0.5       , 1.        , 1.33333333],
       [0.42857143, 0.75      , 1.        ]])