# Numpy Array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,6,],dtype='float32')                              # Floating point array 
a

array([1., 2., 3., 6.], dtype=float32)

In [3]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [4]:
np.zeros((3,5), dtype=int)                                 # Zeros Matrix

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
np.ones((4,5), dtype=float)                                 # Ones Matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((4,5),77)                                      # Full matrix

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [7]:
np.random.normal(1,6,(4,4))

array([[-2.70051441,  4.80875115, -0.66194468, -0.36489532],
       [-6.37220502,  0.15452767,  6.2452984 ,  1.59311302],
       [ 1.14328779,  4.3574703 , -3.70340387,  5.07821347],
       [ 8.73144631, 10.60573722, -5.80709551, -9.07353253]])

In [8]:
np.identity(5, dtype=int)                       # Identity Matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
np.eye(10,dtype=float)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
np.empty(9)

array([1.06133861e-312, 0.00000000e+000, 1.06395697e+224, 3.31712523e-033,
       1.38293876e-047, 3.85166334e-057, 7.48972228e-067, 2.76996634e-085,
       6.27207943e-310])

In [11]:
np.random.randint(10, size=(4,5))

array([[5, 8, 8, 7, 0],
       [5, 0, 1, 4, 0],
       [9, 9, 2, 5, 4],
       [6, 4, 4, 3, 3]])

In [12]:
x1=np.random.randint(14, size=3)
x1

array([ 8, 13,  5])

In [13]:
x1.ndim

1

In [14]:
x1.shape

(3,)

In [15]:
x2=np.random.randint(14,size=(3,4,5))
x2

array([[[ 3,  6,  0, 10, 11],
        [11,  8,  4,  6,  2],
        [11,  0, 10,  0, 11],
        [ 3,  6, 12,  6,  0]],

       [[ 4,  5,  4,  2, 11],
        [ 7,  4,  6,  1,  4],
        [ 6, 13, 11, 12,  9],
        [ 7, 13,  0, 13,  5]],

       [[13,  9,  4,  6,  7],
        [ 6,  1,  7,  1, 12],
        [ 3, 10, 10,  8,  0],
        [ 6,  5, 13,  7,  7]]])

In [16]:
x2.ndim

3

In [17]:
x2.shape

(3, 4, 5)

In [18]:
x2.size

60

In [19]:
x2.dtype

dtype('int32')

In [20]:
x1.dtype

dtype('int32')

In [21]:
print(x2.itemsize)

4


In [22]:
x2.nbytes

240

In [23]:
x2

array([[[ 3,  6,  0, 10, 11],
        [11,  8,  4,  6,  2],
        [11,  0, 10,  0, 11],
        [ 3,  6, 12,  6,  0]],

       [[ 4,  5,  4,  2, 11],
        [ 7,  4,  6,  1,  4],
        [ 6, 13, 11, 12,  9],
        [ 7, 13,  0, 13,  5]],

       [[13,  9,  4,  6,  7],
        [ 6,  1,  7,  1, 12],
        [ 3, 10, 10,  8,  0],
        [ 6,  5, 13,  7,  7]]])

In [24]:
x1

array([ 8, 13,  5])

In [25]:
x=np.random.seed(0)
x=np.random.randint(10, size=(3,3))
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [26]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [27]:
x[0]

array([5, 0, 3])

In [28]:
x[1,1]

7

In [29]:
x[1,-1]

9

In [30]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [31]:
x[0,0]=100

In [32]:
x

array([[100,   0,   3],
       [  3,   7,   9],
       [  3,   5,   2]])

In [33]:
x

array([[100,   0,   3],
       [  3,   7,   9],
       [  3,   5,   2]])

In [34]:
r=np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
r[1:4]

array([1, 2, 3])

In [36]:
r[::2]

array([0, 2, 4, 6, 8])

In [37]:
r[1::2]

array([1, 3, 5, 7, 9])

In [38]:
r[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
r[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
r[5]

5

In [41]:
r[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
r[7::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x

array([[100,   0,   3],
       [  3,   7,   9],
       [  3,   5,   2]])

In [44]:
x=np.random.seed(0)
x=np.random.randint(20, size=(6,6))
x

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [45]:
x

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [46]:
x[2:,1:]

array([[ 6,  7, 14, 17,  5],
       [ 8,  9, 19, 16, 19],
       [15, 15,  0, 18,  3],
       [19, 19, 19, 14,  7]])

In [47]:
x1=np.random.seed(0)
x1=np.random.randint(20, size=(6,6))
x1

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [48]:
x

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [49]:
x

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [50]:
x1

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [51]:
c=np.concatenate([x,x1])
c

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7],
       [12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [52]:
l=np.split(c,3)
l

[array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19]]), array([[ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7],
        [12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12]]), array([[ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19],
        [ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7]])]

In [53]:
type(l)

list

In [54]:
l[0]

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19]])

In [55]:
l[1]

array([[ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7],
       [12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12]])

In [56]:
l

[array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19]]), array([[ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7],
        [12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12]]), array([[ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19],
        [ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7]])]

In [57]:
l[0]

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19]])

In [58]:
c

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7],
       [12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [59]:
l

[array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19]]), array([[ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7],
        [12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12]]), array([[ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19],
        [ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7]])]

In [60]:
sp=np.split(c,3)

In [61]:
sp

[array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19]]), array([[ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7],
        [12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12]]), array([[ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19],
        [ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7]])]

In [62]:
sp

[array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19]]), array([[ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7],
        [12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12]]), array([[ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19],
        [ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7]])]

In [63]:
type(sp)

list

In [64]:
sp[1]

array([[ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7],
       [12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12]])

In [65]:
sp[0]

array([[12, 15,  0,  3,  3,  7],
       [ 9, 19, 18,  4,  6, 12],
       [ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19]])

In [66]:
sp[2]

array([[ 1,  6,  7, 14, 17,  5],
       [13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3],
       [17, 19, 19, 19, 14,  7]])

In [67]:
sp[2]=5

In [68]:
sp[2]

5

In [69]:
sp

[array([[12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12],
        [ 1,  6,  7, 14, 17,  5],
        [13,  8,  9, 19, 16, 19]]), array([[ 5, 15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14,  7],
        [12, 15,  0,  3,  3,  7],
        [ 9, 19, 18,  4,  6, 12]]), 5]

In [70]:
v=np.arange(9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
v**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [72]:
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
x=np.arange(5)

In [74]:
x

array([0, 1, 2, 3, 4])

In [75]:
x+5

array([5, 6, 7, 8, 9])

In [76]:
x*4

array([ 0,  4,  8, 12, 16])

In [77]:
x-6

array([-6, -5, -4, -3, -2])

In [78]:
x-5

array([-5, -4, -3, -2, -1])

In [79]:
x/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [80]:
x//2

array([0, 0, 1, 1, 2], dtype=int32)

In [81]:
-x

array([ 0, -1, -2, -3, -4])

In [82]:
x**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [83]:
x%2

array([0, 1, 0, 1, 0], dtype=int32)

In [84]:
np.add(x,10)

array([10, 11, 12, 13, 14])

In [85]:
np.power(x,3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [86]:
np.mod(x,3)

array([0, 1, 2, 0, 1], dtype=int32)

In [87]:
x=np.array([2,-45,12,-10,6,50])
abs(x)

array([ 2, 45, 12, 10,  6, 50])

In [88]:
x

array([  2, -45,  12, -10,   6,  50])

In [89]:
np.abs(x)

array([ 2, 45, 12, 10,  6, 50])

In [90]:
np.absolute(x)

array([ 2, 45, 12, 10,  6, 50])

In [91]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [92]:
theta=np.linspace(0,np.pi,3)

In [93]:
theta

array([0.        , 1.57079633, 3.14159265])

In [94]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [95]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [96]:
np.pi

3.141592653589793

In [97]:
np.sin(60)

-0.3048106211022167

In [98]:
np.cos(90)

-0.4480736161291701

In [99]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [100]:
np.exp(x)                                  # Exponent 

array([ 2.71828183,  7.3890561 , 20.08553692])

In [101]:
np.exp2(x)

array([2., 4., 8.])

In [102]:
x=1

In [103]:
np.exp(x)

2.718281828459045

In [104]:
np.exp(0)

1.0

In [105]:
np.exp(5)

148.4131591025766

In [106]:
x=[1,2,3,4,5]

In [107]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [108]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [109]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [110]:
x=np.arange(1,6)
y=np.empty(5)

In [111]:
np.multiply(x,10,out=y)
print(y)

[10. 20. 30. 40. 50.]


In [112]:
v=np.arange(1,6)

In [113]:
v

array([1, 2, 3, 4, 5])

In [114]:
np.add.reduce(v)

15

In [115]:
np.multiply.reduce(v)

120

In [116]:
np.subtract.reduce(v)

-13

In [117]:
np.add.accumulate(v)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [118]:
np.multiply.accumulate(v)

array([  1,   2,   6,  24, 120], dtype=int32)

In [119]:
np.multiply.outer(v,v)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [120]:
b=np.arange(10,21)

In [121]:
np.multiply.outer(b,b)

array([[100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200],
       [110, 121, 132, 143, 154, 165, 176, 187, 198, 209, 220],
       [120, 132, 144, 156, 168, 180, 192, 204, 216, 228, 240],
       [130, 143, 156, 169, 182, 195, 208, 221, 234, 247, 260],
       [140, 154, 168, 182, 196, 210, 224, 238, 252, 266, 280],
       [150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300],
       [160, 176, 192, 208, 224, 240, 256, 272, 288, 304, 320],
       [170, 187, 204, 221, 238, 255, 272, 289, 306, 323, 340],
       [180, 198, 216, 234, 252, 270, 288, 306, 324, 342, 360],
       [190, 209, 228, 247, 266, 285, 304, 323, 342, 361, 380],
       [200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400]])

In [122]:
l=np.random.random(100)
sum(l)

48.1083740300764

In [123]:
np.sum(l)

48.10837403007642

In [124]:
l

array([0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077,
       0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559,
       0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
       0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358,
       0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772,
       0.31798318, 0.41426299, 0.0641475 , 0.69247212, 0.56660145,
       0.26538949, 0.52324805, 0.09394051, 0.5759465 , 0.9292962 ,
       0.31856895, 0.66741038, 0.13179786, 0.7163272 , 0.28940609,
       0.18319136, 0.58651293, 0.02010755, 0.82894003, 0.00469

In [125]:
np.sum(l)

48.10837403007642

In [126]:
m=np.random.seed(0)
m=np.random.randint(5)
m

4