# Numpy Functions

In [29]:
import numpy

In [30]:
numpy.__version__

'1.15.4'

In [31]:
import numpy as np

In [32]:
n1d=np.array([10,30,40,50])                          # Single dimensional Numpy array, 1 row and 4 columns
n1d

array([10, 30, 40, 50])

In [33]:
n2d=np.array([[10,20,30,40],[50,60,40,80]])             # Multi dimensional Numpy array, 2 rows and 4 columns
n2d       

array([[10, 20, 30, 40],
       [50, 60, 40, 80]])

In [6]:
n2d.shape                                               # Check shape of Numpy Array

(2, 4)

In [34]:
n2d.shape=(4,2)                                         # Change shape of array (2,4) to (4,2)
n2d

array([[10, 20],
       [30, 40],
       [50, 60],
       [40, 80]])

In [35]:
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,7,2,6]])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 2, 6]])

In [36]:
arr2d.shape                                              # Check shape of numpy array

(3, 4)

In [37]:
type(n1d)

numpy.ndarray

In [11]:
type(arr2d)

numpy.ndarray

In [38]:
nzero=np.zeros([2,2])                                   # Initializing Numpy array with Zeros
nzero

array([[0., 0.],
       [0., 0.]])

In [13]:
nzero1=np.zeros([3,4])
nzero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
nfull=np.full([3,3],10)                                # Initalizing numpy full array by same number
nfull

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [15]:
nfull1=np.full([4,5],55)
nfull1

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [16]:
narange=np.arange(10,20)                                 # Initializing Numpy array within range
narange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
narange1=np.arange(10,100,5)                             # 5 is interval
narange1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [18]:
narange2=np.arange(20)
narange2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
nrandom=np.random.randint(1,100,8)                     # Intializing numpy array with random numbers
nrandom

array([65, 58, 90, 39,  8, 99, 75, 91])

In [20]:
n1=np.array([40,50,30])
n2=np.array([90,80,70])

In [21]:
n1

array([40, 50, 30])

In [22]:
n2

array([90, 80, 70])

In [40]:
np.sum([n1,n2])                                      # Addition of two Numpy Array i.e. addition of both complete array

348

In [24]:
np.sum([n1,n2],axis=0)                                # Addition ( Axis=0 means add array in vertical format)

array([130, 130, 100])

In [25]:
np.sum([n1,n2],axis=1)                                   # Axis=1 means add array in horizontal format

array([120, 240])

In [26]:
n1=np.array([40,15,78])                          # VSTACK for join two array in vertical format
n2=np.array([80,45,90])
np.vstack((n1,n2))

array([[40, 15, 78],
       [80, 45, 90]])

In [27]:
np.hstack((n1,n2))                              # HSTACK for join two array in horizontal format

array([40, 15, 78, 80, 45, 90])

In [28]:
np.column_stack((n1,n2))                       # COLUMN_STACK for join array in column format

array([[40, 80],
       [15, 45],
       [78, 90]])

In [42]:
n=np.array([1,2,65,9,5,5,6,5,5])
n

array([ 1,  2, 65,  9,  5,  5,  6,  5,  5])

In [43]:
n1=np.array([[1,4,55,48],[78,45,16,41]])
n1

array([[ 1,  4, 55, 48],
       [78, 45, 16, 41]])

In [44]:
n1.shape

(2, 4)

In [47]:
nz=np.zeros([4,5])
nz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
no=np.ones([5,4])
no

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
nf=np.full([4,4],12)
nf

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [52]:
na=np.arange(4,10)
na

array([4, 5, 6, 7, 8, 9])

In [53]:
na1=np.arange(10,50,5)
na1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [55]:
ar=np.random.randint(4,50,10)
ar

array([42, 13, 45, 23, 33, 47, 41, 28, 32, 19])

In [56]:
n1.shape

(2, 4)

In [59]:
n1.shape=(4,2)
n1

array([[ 1,  4],
       [55, 48],
       [78, 45],
       [16, 41]])

In [60]:
n

array([ 1,  2, 65,  9,  5,  5,  6,  5,  5])

In [61]:
n1

array([[ 1,  4],
       [55, 48],
       [78, 45],
       [16, 41]])

In [62]:
n2

array([80, 45, 90])

In [63]:
n3=np.array([41,15,43])
n3

array([41, 15, 43])

In [65]:
n4=np.array([70,48,90])
n4

array([70, 48, 90])

In [67]:
np.sum([n3,n4])

307

In [68]:
np.sum([n3,n4], axis=1)

array([ 99, 208])

In [69]:
np.sum([n3,n4],axis=0)

array([111,  63, 133])

In [70]:
np.vstack([n3,n4])

array([[41, 15, 43],
       [70, 48, 90]])

In [71]:
np.hstack([n3,n4])

array([41, 15, 43, 70, 48, 90])

In [72]:
np.column_stack([n3,n4])

array([[41, 70],
       [15, 48],
       [43, 90]])